### PR TITLE
Create schema while building container itself. 

### PR DESCRIPTION
**Pull request by cbzxt**

### CODE REVIEW

**Comment by chiragr** [comment]
Note that in init.sql we are dropping the table before trying to create it in MySql.

While this will not be an issue for the data in MASTER, SCORE and HISTORICAL_SCORE tables as that data will get restored easily via our backend refresh script, but few data in tables like WATCHLIST and USERS will get destroyed permanently between two docker instance reboots.

So either we need to remove the drop table commands for selected tables or split the file into two parts or maybe run it once separately as was happening before.

**Comment by cbzxt** [comment]
@chiragr  Was there any specific reason for dropping the tables? If not then we can just remove the drop command.

**Comment by chiragr** [comment]
It is considered a good practice for a fresh first time setup. As it will make sure the script does clean creation of all DB objects. But I feel it is okay to remove the drop table commands in our use case.

**Comment by cbzxt** [comment]
Yeah. That's what I think as well. I'll remove the drop queries.

**Pull request merged**
